# Generated by Django 6.0.3 on 2026-04-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('tier', models.IntegerField(choices=[(1, 'Deep'), (2, 'Basic'), (3, 'Skip')], default=1)),
                ('active', models.BooleanField(default=True)),
                ('season', models.IntegerField(default=2025)),
                ('avg_goals', models.FloatField(default=2.5)),
                ('avg_corners', models.FloatField(default=10.0)),
                ('avg_cards', models.FloatField(default=3.5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avg_yellows_per_game', models.FloatField(default=3.5)),
                ('avg_reds_per_game', models.FloatField(default=0.1)),
                ('avg_booking_points', models.FloatField(default=38.0)),
                ('games_officiated', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('games_played', models.IntegerField(default=0)),
                ('home_avg_goals_for', models.FloatField(default=1.5)),
                ('home_avg_goals_against', models.FloatField(default=1.2)),
                ('home_avg_corners_for', models.FloatField(default=5.0)),
                ('home_avg_corners_against', models.FloatField(default=4.5)),
                ('home_avg_cards', models.FloatField(default=1.8)),
                ('home_win_rate', models.FloatField(default=0.4)),
                ('home_draw_rate', models.FloatField(default=0.28)),
                ('away_avg_goals_for', models.FloatField(default=1.2)),
                ('away_avg_goals_against', models.FloatField(default=1.5)),
                ('away_avg_corners_for', models.FloatField(default=4.5)),
                ('away_avg_corners_against', models.FloatField(default=5.2)),
                ('away_avg_cards', models.FloatField(default=2.0)),
                ('away_win_rate', models.FloatField(default=0.28)),
                ('away_draw_rate', models.FloatField(default=0.3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.league')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('kickoff', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('total_corners', models.IntegerField(blank=True, null=True)),
                ('total_cards', models.IntegerField(blank=True, null=True)),
                ('graded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.league')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.referee')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fixtures.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fixtures.team')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
    ]
